name: Deploy to GCE

on:
  push:
    branches:
      - main  # デプロイをトリガーするブランチ名

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to GCE
      run: |
        # GCE インスタンスに接続
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null g1308yuta@34.84.65.229 "bash -s" < deploy.sh
